// +build !generate

package hit

import errortrace "github.com/Eun/go-hit/errortrace"

// ⚠️⚠️⚠️ This file was autogenerated by generators/clear/clear ⚠️⚠️⚠️ //

// IClearExpectInt8 provides methods to clear steps.
type IClearExpectInt8 interface {
	IStep
	// Between clears all matching Between steps
	Between(value ...int8) IStep
	// Equal clears all matching Equal steps
	Equal(value ...int8) IStep
	// GreaterOrEqualThan clears all matching GreaterOrEqualThan steps
	GreaterOrEqualThan(value ...int8) IStep
	// GreaterThan clears all matching GreaterThan steps
	GreaterThan(value ...int8) IStep
	// LessOrEqualThan clears all matching LessOrEqualThan steps
	LessOrEqualThan(value ...int8) IStep
	// LessThan clears all matching LessThan steps
	LessThan(value ...int8) IStep
	// NotBetween clears all matching NotBetween steps
	NotBetween(value ...int8) IStep
	// NotEqual clears all matching NotEqual steps
	NotEqual(value ...int8) IStep
	// NotOneOf clears all matching NotOneOf steps
	NotOneOf(value ...int8) IStep
	// OneOf clears all matching OneOf steps
	OneOf(value ...int8) IStep
}
type clearExpectInt8 struct {
	cp callPath
	tr *errortrace.ErrorTrace
}

func newClearExpectInt8(cp callPath) IClearExpectInt8 {
	return &clearExpectInt8{cp: cp, tr: ett.Prepare()}
}
func (v *clearExpectInt8) trace() *errortrace.ErrorTrace {
	return v.tr
}
func (*clearExpectInt8) when() StepTime {
	return cleanStep
}
func (v *clearExpectInt8) callPath() callPath {
	return v.cp
}
func (v *clearExpectInt8) exec(hit *hitImpl) error {
	if err := removeSteps(hit, v.callPath()); err != nil {
		return err
	}
	return nil
}
func (v *clearExpectInt8) Between(value ...int8) IStep {
	return removeStep(v.callPath().Push("Between", int8SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt8) Equal(value ...int8) IStep {
	return removeStep(v.callPath().Push("Equal", int8SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt8) GreaterOrEqualThan(value ...int8) IStep {
	return removeStep(v.callPath().Push("GreaterOrEqualThan", int8SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt8) GreaterThan(value ...int8) IStep {
	return removeStep(v.callPath().Push("GreaterThan", int8SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt8) LessOrEqualThan(value ...int8) IStep {
	return removeStep(v.callPath().Push("LessOrEqualThan", int8SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt8) LessThan(value ...int8) IStep {
	return removeStep(v.callPath().Push("LessThan", int8SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt8) NotBetween(value ...int8) IStep {
	return removeStep(v.callPath().Push("NotBetween", int8SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt8) NotEqual(value ...int8) IStep {
	return removeStep(v.callPath().Push("NotEqual", int8SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt8) NotOneOf(value ...int8) IStep {
	return removeStep(v.callPath().Push("NotOneOf", int8SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt8) OneOf(value ...int8) IStep {
	return removeStep(v.callPath().Push("OneOf", int8SliceToInterfaceSlice(value)))
}
