// +build !generate

package hit

import errortrace "github.com/Eun/go-hit/errortrace"

// ⚠️⚠️⚠️ This file was autogenerated by generators/clear/clear ⚠️⚠️⚠️ //

// IClearExpectUint8 provides methods to clear steps.
type IClearExpectUint8 interface {
	IStep
	// Between clears all matching Between steps
	Between(value ...uint8) IStep
	// Equal clears all matching Equal steps
	Equal(value ...uint8) IStep
	// GreaterOrEqualThan clears all matching GreaterOrEqualThan steps
	GreaterOrEqualThan(value ...uint8) IStep
	// GreaterThan clears all matching GreaterThan steps
	GreaterThan(value ...uint8) IStep
	// LessOrEqualThan clears all matching LessOrEqualThan steps
	LessOrEqualThan(value ...uint8) IStep
	// LessThan clears all matching LessThan steps
	LessThan(value ...uint8) IStep
	// NotBetween clears all matching NotBetween steps
	NotBetween(value ...uint8) IStep
	// NotEqual clears all matching NotEqual steps
	NotEqual(value ...uint8) IStep
	// NotOneOf clears all matching NotOneOf steps
	NotOneOf(value ...uint8) IStep
	// OneOf clears all matching OneOf steps
	OneOf(value ...uint8) IStep
}
type clearExpectUint8 struct {
	cp callPath
	tr *errortrace.ErrorTrace
}

func newClearExpectUint8(cp callPath) IClearExpectUint8 {
	return &clearExpectUint8{cp: cp, tr: ett.Prepare()}
}
func (v *clearExpectUint8) trace() *errortrace.ErrorTrace {
	return v.tr
}
func (*clearExpectUint8) when() StepTime {
	return cleanStep
}
func (v *clearExpectUint8) callPath() callPath {
	return v.cp
}
func (v *clearExpectUint8) exec(hit *hitImpl) error {
	if err := removeSteps(hit, v.callPath()); err != nil {
		return err
	}
	return nil
}
func (v *clearExpectUint8) Between(value ...uint8) IStep {
	return removeStep(v.callPath().Push("Between", uint8SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint8) Equal(value ...uint8) IStep {
	return removeStep(v.callPath().Push("Equal", uint8SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint8) GreaterOrEqualThan(value ...uint8) IStep {
	return removeStep(v.callPath().Push("GreaterOrEqualThan", uint8SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint8) GreaterThan(value ...uint8) IStep {
	return removeStep(v.callPath().Push("GreaterThan", uint8SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint8) LessOrEqualThan(value ...uint8) IStep {
	return removeStep(v.callPath().Push("LessOrEqualThan", uint8SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint8) LessThan(value ...uint8) IStep {
	return removeStep(v.callPath().Push("LessThan", uint8SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint8) NotBetween(value ...uint8) IStep {
	return removeStep(v.callPath().Push("NotBetween", uint8SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint8) NotEqual(value ...uint8) IStep {
	return removeStep(v.callPath().Push("NotEqual", uint8SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint8) NotOneOf(value ...uint8) IStep {
	return removeStep(v.callPath().Push("NotOneOf", uint8SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint8) OneOf(value ...uint8) IStep {
	return removeStep(v.callPath().Push("OneOf", uint8SliceToInterfaceSlice(value)))
}
