// +build !generate

package hit

import errortrace "github.com/Eun/go-hit/errortrace"

// ⚠️⚠️⚠️ This file was autogenerated by generators/clear/clear ⚠️⚠️⚠️ //

// IClearExpectBodyJSONDasel provides methods to clear steps.
type IClearExpectBodyJSONDasel interface {
	IStep
	// Contains clears all matching Contains steps
	Contains(value ...interface{}) IStep
	// Dasel clears all matching Dasel steps
	Dasel(value ...string) IClearExpectBodyJSONDasel
	// Equal clears all matching Equal steps
	Equal(value ...interface{}) IStep
	// JQ clears all matching JQ steps
	JQ(value ...string) IClearExpectBodyJSONJQ
	// Len clears all matching Len steps
	Len() IClearExpectInt
	// NotContains clears all matching NotContains steps
	NotContains(value ...interface{}) IStep
	// NotEqual clears all matching NotEqual steps
	NotEqual(value ...interface{}) IStep
}
type clearExpectBodyJSONDasel struct {
	cp callPath
	tr *errortrace.ErrorTrace
}

func newClearExpectBodyJSONDasel(cp callPath) IClearExpectBodyJSONDasel {
	return &clearExpectBodyJSONDasel{cp: cp, tr: ett.Prepare()}
}
func (v *clearExpectBodyJSONDasel) trace() *errortrace.ErrorTrace {
	return v.tr
}
func (*clearExpectBodyJSONDasel) when() StepTime {
	return cleanStep
}
func (v *clearExpectBodyJSONDasel) callPath() callPath {
	return v.cp
}
func (v *clearExpectBodyJSONDasel) exec(hit *hitImpl) error {
	if err := removeSteps(hit, v.callPath()); err != nil {
		return err
	}
	return nil
}
func (v *clearExpectBodyJSONDasel) Contains(value ...interface{}) IStep {
	return removeStep(v.callPath().Push("Contains", value))
}
func (v *clearExpectBodyJSONDasel) Dasel(value ...string) IClearExpectBodyJSONDasel {
	return newClearExpectBodyJSONDasel(v.callPath().Push("Dasel", stringSliceToInterfaceSlice(value)))
}
func (v *clearExpectBodyJSONDasel) Equal(value ...interface{}) IStep {
	return removeStep(v.callPath().Push("Equal", value))
}
func (v *clearExpectBodyJSONDasel) JQ(value ...string) IClearExpectBodyJSONJQ {
	return newClearExpectBodyJSONJQ(v.callPath().Push("JQ", stringSliceToInterfaceSlice(value)))
}
func (v *clearExpectBodyJSONDasel) Len() IClearExpectInt {
	return newClearExpectInt(v.callPath().Push("Len", nil))
}
func (v *clearExpectBodyJSONDasel) NotContains(value ...interface{}) IStep {
	return removeStep(v.callPath().Push("NotContains", value))
}
func (v *clearExpectBodyJSONDasel) NotEqual(value ...interface{}) IStep {
	return removeStep(v.callPath().Push("NotEqual", value))
}
