// +build !generate

package hit

import errortrace "github.com/Eun/go-hit/errortrace"

// ⚠️⚠️⚠️ This file was autogenerated by generators/clear/clear ⚠️⚠️⚠️ //

// IClearRequestURLQuery provides methods to clear steps.
type IClearRequestURLQuery interface {
	IStep
	// Add clears all matching Add steps
	Add(value ...interface{}) IStep
}
type clearRequestURLQuery struct {
	cp callPath
	tr *errortrace.ErrorTrace
}

func newClearRequestURLQuery(cp callPath) IClearRequestURLQuery {
	return &clearRequestURLQuery{cp: cp, tr: ett.Prepare()}
}
func (v *clearRequestURLQuery) trace() *errortrace.ErrorTrace {
	return v.tr
}
func (*clearRequestURLQuery) when() StepTime {
	return cleanStep
}
func (v *clearRequestURLQuery) callPath() callPath {
	return v.cp
}
func (v *clearRequestURLQuery) exec(hit *hitImpl) error {
	if err := removeSteps(hit, v.callPath()); err != nil {
		return err
	}
	return nil
}
func (v *clearRequestURLQuery) Add(value ...interface{}) IStep {
	return removeStep(v.callPath().Push("Add", value))
}
