// +build !generate

package hit

import errortrace "github.com/Eun/go-hit/errortrace"

// ⚠️⚠️⚠️ This file was autogenerated by generators/clear/clear ⚠️⚠️⚠️ //

// IClearExpectUint16 provides methods to clear steps.
type IClearExpectUint16 interface {
	IStep
	// Between clears all matching Between steps
	Between(value ...uint16) IStep
	// Equal clears all matching Equal steps
	Equal(value ...uint16) IStep
	// GreaterOrEqualThan clears all matching GreaterOrEqualThan steps
	GreaterOrEqualThan(value ...uint16) IStep
	// GreaterThan clears all matching GreaterThan steps
	GreaterThan(value ...uint16) IStep
	// LessOrEqualThan clears all matching LessOrEqualThan steps
	LessOrEqualThan(value ...uint16) IStep
	// LessThan clears all matching LessThan steps
	LessThan(value ...uint16) IStep
	// NotBetween clears all matching NotBetween steps
	NotBetween(value ...uint16) IStep
	// NotEqual clears all matching NotEqual steps
	NotEqual(value ...uint16) IStep
	// NotOneOf clears all matching NotOneOf steps
	NotOneOf(value ...uint16) IStep
	// OneOf clears all matching OneOf steps
	OneOf(value ...uint16) IStep
}
type clearExpectUint16 struct {
	cp callPath
	tr *errortrace.ErrorTrace
}

func newClearExpectUint16(cp callPath) IClearExpectUint16 {
	return &clearExpectUint16{cp: cp, tr: ett.Prepare()}
}
func (v *clearExpectUint16) trace() *errortrace.ErrorTrace {
	return v.tr
}
func (*clearExpectUint16) when() StepTime {
	return cleanStep
}
func (v *clearExpectUint16) callPath() callPath {
	return v.cp
}
func (v *clearExpectUint16) exec(hit *hitImpl) error {
	if err := removeSteps(hit, v.callPath()); err != nil {
		return err
	}
	return nil
}
func (v *clearExpectUint16) Between(value ...uint16) IStep {
	return removeStep(v.callPath().Push("Between", uint16SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint16) Equal(value ...uint16) IStep {
	return removeStep(v.callPath().Push("Equal", uint16SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint16) GreaterOrEqualThan(value ...uint16) IStep {
	return removeStep(v.callPath().Push("GreaterOrEqualThan", uint16SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint16) GreaterThan(value ...uint16) IStep {
	return removeStep(v.callPath().Push("GreaterThan", uint16SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint16) LessOrEqualThan(value ...uint16) IStep {
	return removeStep(v.callPath().Push("LessOrEqualThan", uint16SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint16) LessThan(value ...uint16) IStep {
	return removeStep(v.callPath().Push("LessThan", uint16SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint16) NotBetween(value ...uint16) IStep {
	return removeStep(v.callPath().Push("NotBetween", uint16SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint16) NotEqual(value ...uint16) IStep {
	return removeStep(v.callPath().Push("NotEqual", uint16SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint16) NotOneOf(value ...uint16) IStep {
	return removeStep(v.callPath().Push("NotOneOf", uint16SliceToInterfaceSlice(value)))
}
func (v *clearExpectUint16) OneOf(value ...uint16) IStep {
	return removeStep(v.callPath().Push("OneOf", uint16SliceToInterfaceSlice(value)))
}
