// +build !generate

package hit

import errortrace "github.com/Eun/go-hit/errortrace"

// ⚠️⚠️⚠️ This file was autogenerated by generators/clear/clear ⚠️⚠️⚠️ //

// IClearSendFormValues provides methods to clear steps.
type IClearSendFormValues interface {
	IStep
	// Add clears all matching Add steps
	Add(value ...interface{}) IStep
}
type clearSendFormValues struct {
	cp callPath
	tr *errortrace.ErrorTrace
}

func newClearSendFormValues(cp callPath) IClearSendFormValues {
	return &clearSendFormValues{cp: cp, tr: ett.Prepare()}
}
func (v *clearSendFormValues) trace() *errortrace.ErrorTrace {
	return v.tr
}
func (*clearSendFormValues) when() StepTime {
	return cleanStep
}
func (v *clearSendFormValues) callPath() callPath {
	return v.cp
}
func (v *clearSendFormValues) exec(hit *hitImpl) error {
	if err := removeSteps(hit, v.callPath()); err != nil {
		return err
	}
	return nil
}
func (v *clearSendFormValues) Add(value ...interface{}) IStep {
	return removeStep(v.callPath().Push("Add", value))
}
