// +build !generate

package hit

import errortrace "github.com/Eun/go-hit/errortrace"

// ⚠️⚠️⚠️ This file was autogenerated by generators/clear/clear ⚠️⚠️⚠️ //

// IClearExpectInt32 provides methods to clear steps.
type IClearExpectInt32 interface {
	IStep
	// Between clears all matching Between steps
	Between(value ...int32) IStep
	// Equal clears all matching Equal steps
	Equal(value ...int32) IStep
	// GreaterOrEqualThan clears all matching GreaterOrEqualThan steps
	GreaterOrEqualThan(value ...int32) IStep
	// GreaterThan clears all matching GreaterThan steps
	GreaterThan(value ...int32) IStep
	// LessOrEqualThan clears all matching LessOrEqualThan steps
	LessOrEqualThan(value ...int32) IStep
	// LessThan clears all matching LessThan steps
	LessThan(value ...int32) IStep
	// NotBetween clears all matching NotBetween steps
	NotBetween(value ...int32) IStep
	// NotEqual clears all matching NotEqual steps
	NotEqual(value ...int32) IStep
	// NotOneOf clears all matching NotOneOf steps
	NotOneOf(value ...int32) IStep
	// OneOf clears all matching OneOf steps
	OneOf(value ...int32) IStep
}
type clearExpectInt32 struct {
	cp callPath
	tr *errortrace.ErrorTrace
}

func newClearExpectInt32(cp callPath) IClearExpectInt32 {
	return &clearExpectInt32{cp: cp, tr: ett.Prepare()}
}
func (v *clearExpectInt32) trace() *errortrace.ErrorTrace {
	return v.tr
}
func (*clearExpectInt32) when() StepTime {
	return cleanStep
}
func (v *clearExpectInt32) callPath() callPath {
	return v.cp
}
func (v *clearExpectInt32) exec(hit *hitImpl) error {
	if err := removeSteps(hit, v.callPath()); err != nil {
		return err
	}
	return nil
}
func (v *clearExpectInt32) Between(value ...int32) IStep {
	return removeStep(v.callPath().Push("Between", int32SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt32) Equal(value ...int32) IStep {
	return removeStep(v.callPath().Push("Equal", int32SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt32) GreaterOrEqualThan(value ...int32) IStep {
	return removeStep(v.callPath().Push("GreaterOrEqualThan", int32SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt32) GreaterThan(value ...int32) IStep {
	return removeStep(v.callPath().Push("GreaterThan", int32SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt32) LessOrEqualThan(value ...int32) IStep {
	return removeStep(v.callPath().Push("LessOrEqualThan", int32SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt32) LessThan(value ...int32) IStep {
	return removeStep(v.callPath().Push("LessThan", int32SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt32) NotBetween(value ...int32) IStep {
	return removeStep(v.callPath().Push("NotBetween", int32SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt32) NotEqual(value ...int32) IStep {
	return removeStep(v.callPath().Push("NotEqual", int32SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt32) NotOneOf(value ...int32) IStep {
	return removeStep(v.callPath().Push("NotOneOf", int32SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt32) OneOf(value ...int32) IStep {
	return removeStep(v.callPath().Push("OneOf", int32SliceToInterfaceSlice(value)))
}
