// +build !generate

package hit

import errortrace "github.com/Eun/go-hit/errortrace"

// ⚠️⚠️⚠️ This file was autogenerated by generators/clear/clear ⚠️⚠️⚠️ //

// IClearRequestURLUser provides methods to clear steps.
type IClearRequestURLUser interface {
	IStep
	// Password clears all matching Password steps
	Password(value ...string) IStep
	// Username clears all matching Username steps
	Username(value ...string) IStep
}
type clearRequestURLUser struct {
	cp callPath
	tr *errortrace.ErrorTrace
}

func newClearRequestURLUser(cp callPath) IClearRequestURLUser {
	return &clearRequestURLUser{cp: cp, tr: ett.Prepare()}
}
func (v *clearRequestURLUser) trace() *errortrace.ErrorTrace {
	return v.tr
}
func (*clearRequestURLUser) when() StepTime {
	return cleanStep
}
func (v *clearRequestURLUser) callPath() callPath {
	return v.cp
}
func (v *clearRequestURLUser) exec(hit *hitImpl) error {
	if err := removeSteps(hit, v.callPath()); err != nil {
		return err
	}
	return nil
}
func (v *clearRequestURLUser) Password(value ...string) IStep {
	return removeStep(v.callPath().Push("Password", stringSliceToInterfaceSlice(value)))
}
func (v *clearRequestURLUser) Username(value ...string) IStep {
	return removeStep(v.callPath().Push("Username", stringSliceToInterfaceSlice(value)))
}
