// +build !generate

package hit

import errortrace "github.com/Eun/go-hit/errortrace"

// ⚠️⚠️⚠️ This file was autogenerated by generators/clear/clear ⚠️⚠️⚠️ //

// IClearExpectInt64 provides methods to clear steps.
type IClearExpectInt64 interface {
	IStep
	// Between clears all matching Between steps
	Between(value ...int64) IStep
	// Equal clears all matching Equal steps
	Equal(value ...int64) IStep
	// GreaterOrEqualThan clears all matching GreaterOrEqualThan steps
	GreaterOrEqualThan(value ...int64) IStep
	// GreaterThan clears all matching GreaterThan steps
	GreaterThan(value ...int64) IStep
	// LessOrEqualThan clears all matching LessOrEqualThan steps
	LessOrEqualThan(value ...int64) IStep
	// LessThan clears all matching LessThan steps
	LessThan(value ...int64) IStep
	// NotBetween clears all matching NotBetween steps
	NotBetween(value ...int64) IStep
	// NotEqual clears all matching NotEqual steps
	NotEqual(value ...int64) IStep
	// NotOneOf clears all matching NotOneOf steps
	NotOneOf(value ...int64) IStep
	// OneOf clears all matching OneOf steps
	OneOf(value ...int64) IStep
}
type clearExpectInt64 struct {
	cp callPath
	tr *errortrace.ErrorTrace
}

func newClearExpectInt64(cp callPath) IClearExpectInt64 {
	return &clearExpectInt64{cp: cp, tr: ett.Prepare()}
}
func (v *clearExpectInt64) trace() *errortrace.ErrorTrace {
	return v.tr
}
func (*clearExpectInt64) when() StepTime {
	return cleanStep
}
func (v *clearExpectInt64) callPath() callPath {
	return v.cp
}
func (v *clearExpectInt64) exec(hit *hitImpl) error {
	if err := removeSteps(hit, v.callPath()); err != nil {
		return err
	}
	return nil
}
func (v *clearExpectInt64) Between(value ...int64) IStep {
	return removeStep(v.callPath().Push("Between", int64SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt64) Equal(value ...int64) IStep {
	return removeStep(v.callPath().Push("Equal", int64SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt64) GreaterOrEqualThan(value ...int64) IStep {
	return removeStep(v.callPath().Push("GreaterOrEqualThan", int64SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt64) GreaterThan(value ...int64) IStep {
	return removeStep(v.callPath().Push("GreaterThan", int64SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt64) LessOrEqualThan(value ...int64) IStep {
	return removeStep(v.callPath().Push("LessOrEqualThan", int64SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt64) LessThan(value ...int64) IStep {
	return removeStep(v.callPath().Push("LessThan", int64SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt64) NotBetween(value ...int64) IStep {
	return removeStep(v.callPath().Push("NotBetween", int64SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt64) NotEqual(value ...int64) IStep {
	return removeStep(v.callPath().Push("NotEqual", int64SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt64) NotOneOf(value ...int64) IStep {
	return removeStep(v.callPath().Push("NotOneOf", int64SliceToInterfaceSlice(value)))
}
func (v *clearExpectInt64) OneOf(value ...int64) IStep {
	return removeStep(v.callPath().Push("OneOf", int64SliceToInterfaceSlice(value)))
}
